### ISSUE TITLE
Simple example error...

### ISSUE THREAD

**Issue by acujl** [ellisonleao/pyshorteners#121]
My code:
```
import pyshorteners

s = pyshorteners.Shortener()
print(s.tinyurl.short('www.google.com'))
# prints 'http://tinyurl.com/HASH'
```
Error:
```
Traceback (most recent call last):
  File "(...)/scratch.py", line 11, in <module>
    print(s.tinyurl.short('www.google.com'))
AttributeError: 'Shortener' object has no attribute 'tinyurl'

Process finished with exit code 1
```

**Comment by drkostas** [comment]
Can confirm

**Comment by ellisonleao** [comment]
hey @drkostas @acujl sorry about that.  You are using a version which is not on pypi yet and i will assume that you've tried to install the lib using `pip`, that's why the code is not working.

For old versions you should try:

```python
import pyshorteners
from pyshorteners import Shorteners
s = pyshorteners.Shortener(Shorteners.TINYURL)
shorturl = s.short('http://www.google.com')
print(shorturl)
```

**Comment by drkostas** [comment]
This works fine, thanks

**Comment by Mohammad2002-web** [comment]
It does not work for me 
I have this problem here 

TypeError: exceptions must derive from BaseException
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "shortUrl.py", line 61, in <lambda>
  File "shortUrl.py", line 5, in short_url
  File "pyshorteners\__init__.py", line 39, in __getattr__
AttributeError: 'Shortener' object has no attribute 'bitly'

it works inside pycharm but when I convert the file to the execute file the above error shown
