### ISSUE TITLE
Docs update for 1.0

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/pyshorteners#137]
Current docs are outdated and doesn't have all the features included as well. We must update it with the current shorteners implementations together with some examples as well.

**Comment by lkbhitesh07** [comment]
@ellisonleao hello, I want to give it a shot but I'm totally a new contributor, already read the contribution guides and etc, I'm confused like specifically in which file I should add the docstring, will you please guide me, it'll be a great help

**Comment by e4r7hbug** [comment]
I've previously used `sphinx-apidoc` to generate more [autodoc](https://www.sphinx-doc.org/en/master/usage/quickstart.html#autodoc) blocks, [Foremast docs example](https://github.com/foremast/foremast/blob/6fa5b724ff48bda81db968d73ebc242e1823948c/_docs/conf.py#L359). I would suggest finding a way to run this before `make html`, which is why I put it in `docs/conf.py` previously.

```bash
# Example command to run and generate more https://www.sphinx-doc.org/en/master/usage/quickstart.html#autodoc
sphinx-apidoc --force --output-dir apis ../pyshorteners/
```

I could see a few documentation changes that would be good for this project:

- [ ] How to generate the docs with Sphinx
- [ ] Auto-generate the Python API docs with `sphinx-apidoc`
- [ ] Review shortener Class docstrings to be more like [pyshorteners/shorteners/adfly.py]()
- [ ] Move [CONTRIBUTING.md]() into the Sphinx docs so it's indexed, convert to reStructuredText or configure as described in https://www.sphinx-doc.org/en/master/usage/markdown.html
- [ ] Update the **Building a new Shortener** section in [CONTRIBUTING.md]() to indicate what Exceptions to raise under what conditions
- [ ] Potentially use https://pypi.org/project/sphinxcontrib-programoutput/ to generate the list of available shorteners
  ```rst
  .. program-output:: python -c 'from pyshorteners import Shortener; print("\n".join(Shortener().available_shorteners))'
  ```

I would recommend breaking this up into a lot of Pull Request so others can help and less chances for conflicts. I can also help if needed for Hacktoberfest.

**Comment by ellisonleao** [comment]
Agreed @e4r7hbug , the documentation part is a big project itself. We can use this issue to track the changes. I had some issues on getting the docstring to work with the Google docstring style, the one we are currently using. Currently the code uses the [napoleon extension](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) to get those changes.

**Comment by e4r7hbug** [comment]
Ah, I'm familiar with Google Style and Napoleon. I can help look at some of those.

@lkbhitesh07: Would you like to start with fixing up the way PyPI renders the **Project description**? I'm not sure how familiar you are with Python packaging, Markdown, or reStructuredText. I think that's the easiest and you can use https://test.pypi.org/ to validate. https://packaging.python.org/guides/using-testpypi/

**Comment by e4r7hbug** [comment]
@lkbhitesh07: Are you able to help with updating the other Shortener docstrings?

**Comment by lkbhitesh07** [comment]
@e4r7hbug Sorry i'm not sure about it, because i'm totally new to open source, will you please elaborate it'll be a help.

**Comment by e4r7hbug** [comment]
For the `Shorteners`, it looks like there are still a bunch to review and update in https://github.com/ellisonleao/pyshorteners/tree/master/pyshorteners/shorteners. The docstrings need to look more like https://github.com/ellisonleao/pyshorteners/blob/master/pyshorteners/shorteners/adfly.py. The Class and Method descriptions need to be updated along with Argument and Keyword Argument descriptions.

This list can help track which Classes still need to be reviewed:
* [ ] https://github.com/ellisonleao/pyshorteners/blob/master/pyshorteners/shorteners/bitly.py
* [ ] https://github.com/ellisonleao/pyshorteners/blob/master/pyshorteners/shorteners/chilpit.py
* [ ] https://github.com/ellisonleao/pyshorteners/blob/master/pyshorteners/shorteners/clckru.py
* [ ] https://github.com/ellisonleao/pyshorteners/blob/master/pyshorteners/shorteners/dagd.py
* [ ] https://github.com/ellisonleao/pyshorteners/blob/master/pyshorteners/shorteners/gitio.py
* [ ] https://github.com/ellisonleao/pyshorteners/blob/master/pyshorteners/shorteners/isgd.py
* [ ] https://github.com/ellisonleao/pyshorteners/blob/master/pyshorteners/shorteners/nullpointer.py
* [ ] https://github.com/ellisonleao/pyshorteners/blob/master/pyshorteners/shorteners/osdb.py
* [ ] https://github.com/ellisonleao/pyshorteners/blob/master/pyshorteners/shorteners/owly.py
* [ ] https://github.com/ellisonleao/pyshorteners/blob/master/pyshorteners/shorteners/post.py
* [ ] https://github.com/ellisonleao/pyshorteners/blob/master/pyshorteners/shorteners/qpsru.py
* [ ] https://github.com/ellisonleao/pyshorteners/blob/master/pyshorteners/shorteners/soogd.py
* [ ] https://github.com/ellisonleao/pyshorteners/blob/master/pyshorteners/shorteners/tinycc.py
* [ ] https://github.com/ellisonleao/pyshorteners/blob/master/pyshorteners/shorteners/tinyurl.py
